#!/usr/bin/expect

set timeout 1

while { $timeout == 1 } {
  spawn -noecho ssh -N -T -R22221:localhost:22220 damnedscholar@50.82.72.166
  set time [clock format [clock seconds] -format "%Y.%m.%d (%H:%M:%S)"]
  send_user "$time > Looking for host\n"
  set timeout 0
  wait
  set timeout 1
  send_user "$time > We've encountered an error. Re-running.\n"
}

send_user "$time > Out of the loop."
