#!/usr/bin/expect

set timeout 1

while { $timeout == 1 } {
  spawn -noecho ssh -N -T -R22221:localhost:22220 damnedscholar@50.82.72.166
  send_user "Looking for host"
  set timeout 0
  wait
  set timeout 1
  send_user "We've encountered an error. Re-running."
}

send_user "Out of the loop."
