#!/bin/bash

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


ttg=$(ping -c 1 google.com | awk '/time=/ { print $8 $9 }' | sed 's/time=//')
ms=$(ping -c 1 google.com | awk '/time=/ { print $8 $9 }' | sed 's/time=//' | sed 's/\..ms//')

if [[ ! $ttg ]]; then
  ttg="--.-ms"
fi

echo "$ttg" # full text
echo "$ttg" # short text

# color
if [[ $ms -lt 70 ]]; then
    echo "#87a96b"
elif [[ $ms -ge 70 ]]; then
    echo "#d0c239"
elif [[ $ms -gt 150 ]]; then
    echo "#ada129"
elif [[ $ms -lt 300 ]]; then
    echo "#b83c3c"
fi
